spring:

  application:
    name: shopping-cart


  cloud:
    config:
      uri:
        http://localhost:8888

  config:
    import: "optional:configserver:"

    spring:
      h2:
        console:
          enabled: true
          path: /h2
      datasource:
        url: jdbc:h2:file:~/test
        username: sa
        password:
        driverClassName: org.h2.Driver







